name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  

jobs:

  building:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5.0.0

      - name: Building
        run: |
          echo "BUILDING ......"
          mvn clean package -DskipTests

      - name: Run
        run: |
          echo "RUN ......"
          docker build -t spring-petclinic .
          docker run -d -p 9193:9966 --name petclinic_container spring-petclinic
      
      
#  docker rm -f petclinic_container
  
#  checkout:
 #   runs-on: ubuntu-latest
  #    steps: 
   #   - uses: actions/checkout@v5.0.0
  
#  build:

 #   runs-on: ubuntu-latest

  #  steps:
   # - uses: actions/checkout@v4
  #  - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
